# Server / Simple Model Config
server:
  number: 1
  model_type: "lightgbm" # .py name => xgboost / lgbm
  mode: "kfold-train" # kfold-train / train Two options
  pre_process_type:
    - "submit"
print:
  evaluation-period: 100 # Only input int
# Data Config
data:
  k-fold:
    n_folds: 5
    shuffle: True
  random_state: 42
  path: "/data/processed/V5-2024-10-16-YDS-APT-RANK-RecentD.csv" #V6
  output_path: "/data/output" # 해당 파라미터는 수정하지 마세요.
  target: "deposit"
  type_feature: "_type" # train/test type feature

## Model Config

lightgbm:
  objective: 'regression'
  metric: 'mae'
  boosting_type: 'gbdt'
  num_leaves: 31
  learning_rate: 0.05
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  num_boost_round: 1000

xgboost:
  objective: "reg:absoluteerror"
  eval_metric: "mae"
  max_depth: 6
  subsample: 0.8
  colsample_bytree: 0.8
  #  num_class: 4
  learning_rate: 0.05
  num_boost_round: 1000
  early_stopping_rounds: 50
  verbose: 10

#tree_method: 'gpu_hist' #GPU 사용시
#predictor: 'gpu_predictor' #GPU 사용시

